@startuml
interface IEncodePassword {
    EncodePassword(password:string) : Tuple<byte[], byte[]>
    EncodePasswordWithKey(encodeKey:byte[], password:string) : byte[]
}
class Decryption {
    + EncodePassword(password:string) : Tuple<byte[], byte[]>
    + EncodePasswordWithKey(encodeKey:byte[], password:string) : byte[]
}
IEncodePassword <|-- Decryption
@enduml
