@startuml
!include .\\Controllers\AccountController.puml
/'!include .\\Controllers\ChoicesController.puml
!include .\\Controllers\JobTitleController.puml
!include .\\Controllers\QuestionsController.puml
!include .\\Controllers\UserController.puml
!include .\\Controllers\WalkthroughController.puml
!include .\\Controllers\WalktorughAppApiController.puml'/
/'!include .\\DAL\ICreate.puml
!include .\\DAL\IDelete.puml
!include .\\DAL\IGet.puml
!include .\\DAL\IUpdate.puml
!include .\\Data\DataContext.puml'/
/'!include .\\Entities\Choice.puml
!include .\\Entities\JobTitle.puml
!include .\\Entities\LoginDetails.puml
!include .\\Entities\NewChoice.puml
!include .\\Entities\NewJobTitle.puml
!include .\\Entities\NewQuestion.puml
!include .\\Entities\NewWalkthrough.puml
!include .\\Entities\Question.puml
!include .\\Entities\User.puml
!include .\\Entities\UserRegistration.puml
!include .\\Entities\Walkthrough.puml
!include .\\Exceptions\QuestionNotFoundException.puml'/
!include .\\Helpers\IEncodePassword.puml
/'!include .\\DAL\Choices\CreateChoices.puml
!include .\\DAL\Choices\DeleteChoices.puml
!include .\\DAL\Choices\GetChoices.puml
!include .\\DAL\Choices\ICreateChoices.puml
!include .\\DAL\Choices\IGetChoices.puml
!include .\\DAL\Choices\UpdateChoice.puml
!include .\\DAL\JobTitles\CreateJob.puml
!include .\\DAL\JobTitles\DeleteJob.puml
!include .\\DAL\JobTitles\GetJobs.puml
!include .\\DAL\JobTitles\UpdateJob.puml
!include .\\DAL\Questions\CreateQuestion.puml
!include .\\DAL\Questions\DeleteQuestion.puml
!include .\\DAL\Questions\GetQuestions.puml
!include .\\DAL\Questions\IGetQuestions.puml
!include .\\DAL\Questions\UpdateQuestion.puml
!include .\\DAL\Walkthroughs\CreateWalkthrough.puml
!include .\\DAL\Walkthroughs\DeleteWalkthrough.puml
!include .\\DAL\Walkthroughs\GetWalkthroughs.puml
!include .\\DAL\Walkthroughs\ICreateWalkthrough.puml
!include .\\DAL\Walkthroughs\UpdateWalkthrough.puml'/
@enduml
